@host=http://localhost:5295
@userId=7879c745-448c-425b-9375-de9f1db871ce
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDA4ZjI5Yi1kYmRhLTQxOTgtYTI2Yi1mZWI4MDkzODRkYzMiLCJnaXZlbl9uYW1lIjoiQm9iYnkiLCJmYW1pbHlfbmFtZSI6IlRhYmxlcyIsImp0aSI6ImNhMGMyZjUxLTdlOGMtNGMxYi1iOGI3LTEwNDViYzU4ZTM4MSIsImV4cCI6MTcxODgzMTUxNiwiaXNzIjoiRXhwZW5zZU1hbmFnZXIiLCJhdWQiOiJFeHBlbnNlTWFuYWdlclVzZXIifQ.uCMQlfV2XpvAcTEU4Bnblog7D-MGWvQInmmc_slnGgI
POST {{host}}/users/{{userId}}/periods
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "startDate": "2024-01-01",
    "endDate": "2024-01-05"
}
