GET  http://localhost:5295/periods
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTE1Y2YwMC02YmEzLTRhODgtYjhkZi1mMGVmYWMzYzQwOWMiLCJnaXZlbl9uYW1lIjoiQm9iYnkiLCJmYW1pbHlfbmFtZSI6IlRhYmxlcyIsImp0aSI6IjgwN2NiNDE2LTQwYTAtNGUwZC04YjM0LWUyODhiN2NmNjA1YyIsImV4cCI6MTcxODYwNDA0MywiaXNzIjoiRXhwZW5zZU1hbmFnZXIiLCJhdWQiOiJFeHBlbnNlTWFuYWdlclVzZXIifQ.p1fwKNbcHkm8dDUWADan9luW_mYRnwXFD7giXUk4Vi8