POST http://localhost:5295/auth/register
Content-Type: application/json

{
    "firstName": "Bobby",
    "lastName": "Tables",
    "username": "boobles",
    "email": "bobbles@example.com",
    "password": "Amiko69!"
}